dist: xenial
sudo: required

language:
  - cpp

cache: ccache

compiler:
  - clang
  - gcc

cache: apt

before_install:
  - sudo add-apt-repository -y ppa:qpid/released
  - sudo apt-get update -qq

install:
  - sudo apt-get install qpidd libqmf2-dev libqpidbroker-dev libqpidclient-dev libqpidcommon-dev libqpidmessaging-dev libqpidtypes-dev libboost-log-dev || true

before_script:
  - mkdir build
  - cd build
  - touch QpidConfig.cmake
  - cmake -DBUILD_SYSTEM_TESTS=on -DQpid_DIR="$(pwd)" -DQpid_FOUND=True -DQpid_INCLUDE_DIRS=/usr/include -DQpid_LIBRARIES="/usr/lib/x86_64-linux-gnu/libqpidmessaging.so;/usr/lib/x86_64-linux-gnu/libqpidtypes.so" ..
  - export QPID_CONNECTION_OPTIONS="{transport:tcp, protocol:amqp0-10}"
  - qpidd -d

script:
  - make -j$(getconf _NPROCESSORS_ONLN)
  - make test cxxsystemtest
